export default {
  MOVIES: 'MOVIES',
  MOVIES_CURRENT_PAGE: 'MOVIES_CURRENT_PAGE',
  TOGGLE_LOADER: 'TOGGLE_LOADER',
  REMOVE_MOVIES: 'REMOVE_MOVIES',
  TOGGLE_SEARCH: 'TOGGLE_SEARCH',
  SHOW_TOAST_NOTIFY: 'SHOW_TOAST_NOTIFY',
};
